### ISSUE TITLE
Compile-time network error, but my network is normal, please point out, thank you.

### ISSUE THREAD

**Issue by bookchainfun** [itleaks/js4eos#10]
js4eos  compile2  -o ./contracts/test/test.wasm ./contracts/test/src/test.cpp
fail due to network or error, please check network and try again
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\lib\compile.js:28:21)
    at Request.self.callback (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by itleaks** [comment]
> js4eos compile2 -o ./contracts/test/test.wasm ./contracts/test/src/test.cpp
> fail due to network or error, please check network and try again
> SyntaxError: Unexpected token < in JSON at position 0
> at JSON.parse ()
> at Request._callback (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\lib\compile.js:28:21)
> at Request.self.callback (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:185:22)
> at Request.emit (events.js:182:13)
> at Request. (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:1161:10)
> at Request.emit (events.js:182:13)
> at IncomingMessage. (C:\Users\eos\AppData\Roaming\npm\node_modules\js4eos\node_modules\request\request.js:1083:12)
> at Object.onceWrapper (events.js:273:13)
> at IncomingMessage.emit (events.js:187:15)
> at endReadableNT (_stream_readable.js:1094:12)

Try it again. Sometimes server is busy so it fails to serve your request.
