### ISSUE TITLE
编译报错，网络错误

### ISSUE THREAD

**Issue by github10000** [itleaks/js4eos#15]
用这种方式编译：js4eos compile2 -g xxx.abi xxx.cpp --contract contractclass

报下面的错：
fail due to network or error, please check network and try again
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/js4eos/lib/compile.js:28:21)
    at self.callback (/usr/local/lib/node_modules/js4eos/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/usr/local/lib/node_modules/js4eos/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

**Comment by gwl1135438834** [comment]
同样，解决了吗？

**Comment by JachinLi** [comment]
我也遇到了同样的问题，与作者联系过，该项目所使用的编译服务器不可用了。作者建议寻找其他的eos合约编译工具。我目前是用的eos studio，能集开发、编译、部署、调用与一身，很方便。可以把编译后生成的wasm、abi文件拷贝到cpp项目位置下，再js4eos deploy xx，即可使用。
