### ISSUE TITLE
编译合约报错

### ISSUE THREAD

**Issue by LucienSong** [itleaks/js4eos#8]
编译合约报错，但是编译hello合约又可以。
```
anonymous$ js4eos dapp compile eosio.token
TypeError: Cannot read property 'kylin' of undefined
    at compile (/usr/local/lib/node_modules/js4eos/cmds/dapp_cmds/compile.js:35:59)
    at Object.exports.handler (/usr/local/lib/node_modules/js4eos/cmds/dapp_cmds/compile.js:76:5)
    at Object.self.runCommand (/usr/local/lib/node_modules/js4eos/node_modules/yargs/lib/command.js:231:22)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:990:30)
    at Object.self.runCommand (/usr/local/lib/node_modules/js4eos/node_modules/yargs/lib/command.js:202:45)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:930:19)
    at startCmd (/usr/local/lib/node_modules/js4eos/js4eos:8:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/js4eos/js4eos:28:5)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

**Comment by itleaks** [comment]
> 编译合约报错，但是编译hello合约又可以。
> 
> ```
> anonymous$ js4eos dapp compile eosio.token
> TypeError: Cannot read property 'kylin' of undefined
>     at compile (/usr/local/lib/node_modules/js4eos/cmds/dapp_cmds/compile.js:35:59)
>     at Object.exports.handler (/usr/local/lib/node_modules/js4eos/cmds/dapp_cmds/compile.js:76:5)
>     at Object.self.runCommand (/usr/local/lib/node_modules/js4eos/node_modules/yargs/lib/command.js:231:22)
>     at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:990:30)
>     at Object.self.runCommand (/usr/local/lib/node_modules/js4eos/node_modules/yargs/lib/command.js:202:45)
>     at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:990:30)
>     at Object.get [as argv] (/usr/local/lib/node_modules/js4eos/node_modules/yargs/yargs.js:930:19)
>     at startCmd (/usr/local/lib/node_modules/js4eos/js4eos:8:3)
>     at Object.<anonymous> (/usr/local/lib/node_modules/js4eos/js4eos:28:5)
>     at Module._compile (internal/modules/cjs/loader.js:722:30)
> ```

需要在js4eos_config.js添加你的合约的部署配置,比如eosio.token，就需要添加下面的内容
deploy:{
        eosio.token:{
            jungle:'xxxx', //replace contract account to your account
            kylin:'xxxx', //replace contract account to your account
        },
}

**Comment by itleaks** [comment]
同时，非常感谢反馈，最新版本已经添加了更加友好的提示信息，请更新
npm install -g js4eos
